const types = {
  CREATE_BUDGET: "BUDGETS_CREATE_BUDGET",
  UPDATE_BUDGET: "BUDGETS_UPDATE_BUDGET",
  DELETE_BUDGET: "BUDGETS_DELETE_BUDGET",
  UPDATE_ALL_BUDGETS_FROM_FIRESTORE: "BUDGETS_ALL_BUDGETS_FROM_FIRESTORE",
} as const;

export default types;
