const types = {
  CREATE_EXPENSE: "EXPENSES_CREATE_EXPENSE",
  UPDATE_EXPENSE: "EXPENSES_UPDATE_EXPENSE",
  DELETE_EXPENSE: "EXPENSES_DELETE_EXPENSE",
  UPDATE_ALL_EXPENSES_FROM_FIRESTORE: "UPDATE_ALL_EXPENSES_FROM_FIRESTORE",
} as const;

export default types;
