const types = {
  CREATE_CATEGORY: "CATEGORIES_CREATE_CATEGORY",
  UPDATE_CATEGORY: "CATEGORIES_UPDATE_CATEGORY",
  DELETE_CATEGORY: "CATEGORIES_DELETE_CATEGORY",
  UPDATE_ALL_CATEGORIES_FROM_FIRESTORE:
    "CATEGORIES_ALL_CATEGORIES_FROM_FIRESTORE",
} as const;

export default types;
